name: Build csctl-openstack binary
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-go

      # Load Golang cache build from GitHub
      - name: build go binary
        run: |
          go build -o csctl-openstack main.go
