name: "Schedule - Check links"
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
# yamllint disable rule:line-length
jobs:
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    if: github.repository == 'SovereignCloudStack/csctl-plugin-openstack'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1
        id: generate-token
        with:
          app-id: ${{ secrets.SCS_APP_ID }}
          private-key: ${{ secrets.SCS_APP_PRIVATE_KEY }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          args: --config .lychee.toml ./*.md  ./docs/**/*.md
          output: ./lychee.md
          format: markdown

      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2
        with:
          state: open
          labels: |
            link-checker

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5
        with:
          title: Link Checker Dashboard
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee.md
          token: "${{ steps.generate-token.outputs.token }}"
          labels: |
            link-checker
